name: locor
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch=2.5
  - ipykernel
  - matplotlib
  - mypy
  - pip
  - pylint
  - isort
  - black
  - twine
  - tqdm
  - pip:
    - nibabel
    - git+https://github.com/honkamj/composable-mapping@dev